name: Deploy Frontend to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          # Your deployment script or commands to sync files to S3
          # Example using AWS CLI:
          aws s3 sync ./code_file/index.html s3://every-065408

      - name: Invalidate CloudFront Cache
        run: |
          # Your script or commands to invalidate CloudFront cache
          # Example using AWS CLI:
          aws cloudfront create-invalidation --distribution-id https://d1z3lrvu2yn7k9.cloudfront.net --paths "/*"
